[[materials]] # red
albedo = [1.0, 0.3, 0.3]
roughness = 0.8

[[materials]] # green
albedo = [0.3, 1.0, 0.3]
roughness = 0.1

[[materials]] # light grey
albedo = [0.5, 0.5, 0.5]
roughness = 0.5

[[materials]] # dark grey
albedo = [0.7, 0.7, 0.7]
roughness = 0.3

[[geometry]]
type = "sphere"
radius = 0.5
position = [1.0, 0.0, -1.0]
material = 0

[[geometry]]
type = "plane"
normal = [0.0, 1.0, 0.0]
position = [0.0, -0.5, 0.0]
material = 2
material2 = 3

[[geometry]]
type = "transform"
rotation = [0.0, 45.0, 0.0]

  [geometry.child]
  type = "aabb"
  min = [-0.5, -0.5, -0.5]
  max = [0.5, 0.5, 0.5]
  material = 1

[[lights]]
type = "directional"
direction = [-0.7, -1.0, 0.4]
intensity = 0.7

[[lights]]
type = "point"
position = [1.0, 1.0, 1.0]
intensity = 0.5
