camera_position = [-2.5, 2.0, -0.5]
# camera_forward_direction = [1.0, -0.5, 0.0]
camera_lookat = [1.0, 0.0, -0.5]
vertical_fov = 50.0
sky_colour = [0.06, 0.06, 0.12]

[[materials]] # red
albedo = [1.0, 0.3, 0.3]
roughness = 0.8

[[materials]] # green
albedo = [0.3, 1.0, 0.3]
roughness = 0.1
emission_colour = [0.3, 1.0, 0.3]
emission_power = 0.3

[[materials]] # light grey
albedo = [0.5, 0.5, 0.5]
roughness = 0.5

[[materials]] # dark grey
albedo = [0.7, 0.7, 0.7]
roughness = 0.3

[[materials]] # emissive orange
albedo = [0.8, 0.5, 0.2]
roughness = 0.1
emission_colour = [0.8, 0.5, 0.2]
emission_power = 5.0

[[geometry]]
type = "sphere"
radius = 0.5
position = [2.0, 0.5, -2.0]
material = 4

[[geometry]]
type = "plane"
normal = [0.0, 1.0, 0.0]
position = [0.0, -0.5, 0.0]
material = 2
material2 = 3

[[geometry]]
type = "transform"
rotation = [0.0, 45.0, 0.0]

[geometry.child]
type = "sdfaabb"
min = [-0.5, -0.5, -0.5]
max = [0.5, 0.5, 0.5]
rounded = 0.1
material = 1

[[geometry]]
type = "sdfconstructive"
operation = "union"
smoothing = 30.0
material = 0

[geometry.left]
type = "sdfsphere"
radius = 0.5
position = [2.0, 0.0, 0.0]

[geometry.right]
type = "sdfaabb"
min = [2.0, -0.5, 0.0]
max = [3.0, 0.5, 1.0]

# [[lights]]
# type = "directional"
# direction = [-0.7, -1.0, 0.4]
# intensity = 0.7
#
[[lights]]
type = "point"
position = [1.0, 1.0, 1.0]
intensity = 0.1
